version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tg-bot
    restart: always
    env_file:
      - .env
    depends_on:
      - mongo
      - redis

  mongo:
    image: mongo:8.0.0-rc4-jammy
    container_name: mongo
    restart: always
    env_file:
      - .env
    volumes:
      - ./dockerstorage/mongo:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_PASSWORD}
    ports:
      - "${DB_PORT}:27017"

  redis:
    image: redis:7.4-rc1-alpine3.20
    container_name: redis
    restart: always
    env_file:
      - .env
    volumes:
      - ./dockerstorage/redis:/data
    ports:
      - "${REDIS_PORT}:6379"
